// Country code → major cities mapping.
// Countries not present here will show a freetext input instead of a dropdown.
export const COUNTRY_CITIES: Record<string, string[]> = {
  // ─── Middle East ──────────────────────────────────────────────────────────
  AE: [
    'Dubai',
    'Abu Dhabi',
    'Sharjah',
    'Ajman',
    'Ras Al Khaimah',
    'Al Ain',
    'Fujairah',
    'Umm Al Quwain',
  ],
  SA: [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Khobar',
    'Dhahran',
    'Jubail',
    'Tabuk',
    'Abha',
    'Yanbu',
    'Najran',
  ],
  QA: ['Doha', 'Lusail', 'Al Wakrah', 'Al Khor', 'Dukhan', 'Mesaieed', 'Al Rayyan'],
  KW: ['Kuwait City', 'Hawalli', 'Salmiya', 'Ahmadi', 'Jahra', 'Farwaniya', 'Mangaf'],
  BH: ['Manama', 'Muharraq', 'Riffa', 'Isa Town', 'Sitra', 'Hamad Town', 'Jidhafs'],
  OM: ['Muscat', 'Salalah', 'Sohar', 'Nizwa', 'Sur', 'Seeb', 'Buraimi', 'Ibri', 'Rustaq'],
  EG: [
    'Cairo',
    'Alexandria',
    'Giza',
    'Port Said',
    'Suez',
    'Luxor',
    'Aswan',
    'Sharm El Sheikh',
    'Hurghada',
    'Mansoura',
    'Tanta',
    'Ismailia',
  ],
  LB: ['Beirut', 'Tripoli', 'Sidon', 'Tyre', 'Jounieh', 'Byblos', 'Zahle', 'Nabatiyeh'],
  JO: ['Amman', 'Zarqa', 'Irbid', 'Aqaba', 'Salt', 'Madaba', 'Jerash', 'Karak', 'Mafraq'],
  IQ: [
    'Baghdad',
    'Basra',
    'Erbil',
    'Mosul',
    'Najaf',
    'Karbala',
    'Sulaymaniyah',
    'Kirkuk',
    'Nasiriyah',
  ],
  IR: [
    'Tehran',
    'Mashhad',
    'Isfahan',
    'Karaj',
    'Tabriz',
    'Shiraz',
    'Ahvaz',
    'Qom',
    'Rasht',
    'Kermanshah',
  ],
  SY: ['Damascus', 'Aleppo', 'Homs', 'Latakia', 'Hama', 'Tartus', 'Deir ez-Zor', 'Al-Bab'],
  YE: ['Sanaa', 'Aden', 'Taiz', 'Hudaydah', 'Mukalla', 'Ibb', 'Dhamar'],
  PS: ['Jerusalem', 'Gaza City', 'Ramallah', 'Nablus', 'Hebron', 'Jenin', 'Bethlehem', 'Jericho'],
  IL: [
    'Tel Aviv',
    'Jerusalem',
    'Haifa',
    'Rishon LeZion',
    'Petah Tikva',
    'Ashdod',
    'Netanya',
    'Beer Sheva',
    'Holon',
    'Ramat Gan',
  ],

  // ─── North America ────────────────────────────────────────────────────────
  US: [
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Francisco',
    'Seattle',
    'Denver',
    'Nashville',
    'Boston',
    'Miami',
    'Atlanta',
    'Portland',
    'Las Vegas',
    'Minneapolis',
  ],
  CA: [
    'Toronto',
    'Montreal',
    'Vancouver',
    'Calgary',
    'Edmonton',
    'Ottawa',
    'Winnipeg',
    'Quebec City',
    'Hamilton',
    'Kitchener',
    'Halifax',
    'Victoria',
    'Saskatoon',
    'Regina',
  ],
  MX: [
    'Mexico City',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Toluca',
    'Tijuana',
    'León',
    'Ciudad Juárez',
    'Mérida',
    'San Luis Potosí',
    'Aguascalientes',
    'Hermosillo',
    'Culiacán',
  ],

  // ─── Europe ───────────────────────────────────────────────────────────────
  GB: [
    'London',
    'Birmingham',
    'Manchester',
    'Glasgow',
    'Liverpool',
    'Leeds',
    'Sheffield',
    'Edinburgh',
    'Bristol',
    'Leicester',
    'Coventry',
    'Nottingham',
    'Cardiff',
    'Belfast',
    'Southampton',
    'Newcastle',
    'Cambridge',
    'Oxford',
  ],
  DE: [
    'Berlin',
    'Hamburg',
    'Munich',
    'Cologne',
    'Frankfurt',
    'Stuttgart',
    'Düsseldorf',
    'Dortmund',
    'Essen',
    'Leipzig',
    'Bremen',
    'Dresden',
    'Hanover',
    'Nuremberg',
    'Duisburg',
    'Bonn',
    'Mannheim',
  ],
  FR: [
    'Paris',
    'Marseille',
    'Lyon',
    'Toulouse',
    'Nice',
    'Nantes',
    'Strasbourg',
    'Montpellier',
    'Bordeaux',
    'Lille',
    'Rennes',
    'Reims',
    'Saint-Étienne',
    'Toulon',
    'Grenoble',
    'Dijon',
  ],
  IT: [
    'Rome',
    'Milan',
    'Naples',
    'Turin',
    'Palermo',
    'Genoa',
    'Bologna',
    'Florence',
    'Bari',
    'Catania',
    'Venice',
    'Verona',
    'Padua',
    'Trieste',
    'Brescia',
  ],
  ES: [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Seville',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Las Palmas',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Valladolid',
    'Vigo',
    'Gijón',
  ],
  NL: [
    'Amsterdam',
    'Rotterdam',
    'The Hague',
    'Utrecht',
    'Eindhoven',
    'Tilburg',
    'Almere',
    'Groningen',
    'Breda',
    'Nijmegen',
  ],
  BE: [
    'Brussels',
    'Antwerp',
    'Ghent',
    'Charleroi',
    'Liège',
    'Bruges',
    'Namur',
    'Leuven',
    'Mons',
  ],
  CH: [
    'Zurich',
    'Geneva',
    'Basel',
    'Bern',
    'Lausanne',
    'Winterthur',
    'Lucerne',
    'St. Gallen',
    'Lugano',
  ],
  AT: [
    'Vienna',
    'Graz',
    'Linz',
    'Salzburg',
    'Innsbruck',
    'Klagenfurt',
    'Villach',
    'Wels',
    'Sankt Pölten',
  ],
  SE: [
    'Stockholm',
    'Gothenburg',
    'Malmö',
    'Uppsala',
    'Västerås',
    'Örebro',
    'Linköping',
    'Helsingborg',
    'Jönköping',
    'Norrköping',
  ],
  NO: [
    'Oslo',
    'Bergen',
    'Stavanger',
    'Trondheim',
    'Drammen',
    'Fredrikstad',
    'Kristiansand',
    'Tromsø',
  ],
  DK: ['Copenhagen', 'Aarhus', 'Odense', 'Aalborg', 'Esbjerg', 'Randers', 'Kolding', 'Horsens'],
  FI: [
    'Helsinki',
    'Espoo',
    'Tampere',
    'Vantaa',
    'Oulu',
    'Turku',
    'Jyväskylä',
    'Lahti',
    'Kuopio',
  ],
  IE: ['Dublin', 'Cork', 'Limerick', 'Galway', 'Waterford', 'Drogheda', 'Dundalk', 'Bray'],
  PT: [
    'Lisbon',
    'Porto',
    'Vila Nova de Gaia',
    'Braga',
    'Setúbal',
    'Coimbra',
    'Funchal',
    'Almada',
    'Aveiro',
  ],
  PL: [
    'Warsaw',
    'Kraków',
    'Łódź',
    'Wrocław',
    'Poznań',
    'Gdańsk',
    'Szczecin',
    'Bydgoszcz',
    'Lublin',
    'Katowice',
    'Białystok',
    'Gdynia',
    'Toruń',
  ],
  RO: [
    'Bucharest',
    'Cluj-Napoca',
    'Timișoara',
    'Iași',
    'Constanța',
    'Craiova',
    'Brașov',
    'Galați',
    'Ploiești',
  ],
  GR: [
    'Athens',
    'Thessaloniki',
    'Patras',
    'Piraeus',
    'Larissa',
    'Heraklion',
    'Volos',
    'Ioannina',
  ],
  CZ: [
    'Prague',
    'Brno',
    'Ostrava',
    'Plzen',
    'Liberec',
    'Olomouc',
    'Hradec Králové',
    'Pardubice',
  ],
  HU: [
    'Budapest',
    'Debrecen',
    'Miskolc',
    'Szeged',
    'Pécs',
    'Győr',
    'Nyíregyháza',
    'Kecskemét',
  ],
  UA: ['Kyiv', 'Kharkiv', 'Odessa', 'Dnipro', 'Zaporizhzhia', 'Lviv', 'Kryvyi Rih', 'Mykolaiv'],
  RU: [
    'Moscow',
    'Saint Petersburg',
    'Novosibirsk',
    'Yekaterinburg',
    'Kazan',
    'Chelyabinsk',
    'Omsk',
    'Samara',
    'Ufa',
    'Rostov-on-Don',
    'Krasnoyarsk',
    'Perm',
    'Volgograd',
    'Nizhny Novgorod',
  ],
  HR: ['Zagreb', 'Split', 'Rijeka', 'Osijek', 'Zadar', 'Pula', 'Varaždin'],
  AL: ['Tirana', 'Durrës', 'Vlorë', 'Elbasan', 'Shkodër', 'Korçë', 'Fier'],
  TR: [
    'Istanbul',
    'Ankara',
    'Izmir',
    'Bursa',
    'Adana',
    'Gaziantep',
    'Antalya',
    'Konya',
    'Mersin',
    'Diyarbakır',
    'Kayseri',
    'Samsun',
    'Denizli',
  ],

  // ─── Asia-Pacific ─────────────────────────────────────────────────────────
  IN: [
    'Mumbai',
    'Delhi',
    'Bangalore',
    'Chennai',
    'Hyderabad',
    'Ahmedabad',
    'Pune',
    'Kolkata',
    'Surat',
    'Jaipur',
    'Lucknow',
    'Kanpur',
    'Nagpur',
    'Visakhapatnam',
    'Indore',
    'Bhopal',
    'Patna',
    'Vadodara',
  ],
  PK: [
    'Karachi',
    'Lahore',
    'Islamabad',
    'Rawalpindi',
    'Faisalabad',
    'Multan',
    'Hyderabad',
    'Gujranwala',
    'Peshawar',
    'Quetta',
    'Sialkot',
    'Bahawalpur',
  ],
  BD: ['Dhaka', 'Chittagong', 'Sylhet', 'Rajshahi', 'Khulna', 'Comilla', 'Gazipur'],
  CN: [
    'Shanghai',
    'Beijing',
    'Guangzhou',
    'Shenzhen',
    'Chengdu',
    'Tianjin',
    'Wuhan',
    "Xi'an",
    'Hangzhou',
    'Nanjing',
    'Chongqing',
    'Suzhou',
    'Dongguan',
    'Foshan',
    'Shenyang',
    'Harbin',
    'Qingdao',
  ],
  JP: [
    'Tokyo',
    'Yokohama',
    'Osaka',
    'Nagoya',
    'Sapporo',
    'Fukuoka',
    'Kobe',
    'Kyoto',
    'Kawasaki',
    'Saitama',
    'Hiroshima',
    'Sendai',
    'Chiba',
    'Niigata',
    'Shizuoka',
  ],
  KR: [
    'Seoul',
    'Busan',
    'Incheon',
    'Daegu',
    'Daejeon',
    'Gwangju',
    'Suwon',
    'Ulsan',
    'Changwon',
    'Seongnam',
    'Goyang',
    'Yongin',
    'Jeju City',
  ],
  SG: ['Singapore'],
  HK: ['Hong Kong'],
  TW: [
    'Taipei',
    'Kaohsiung',
    'Taichung',
    'Tainan',
    'Hsinchu',
    'Keelung',
    'Taoyuan',
    'Chiayi',
  ],
  ID: [
    'Jakarta',
    'Surabaya',
    'Bandung',
    'Medan',
    'Semarang',
    'Palembang',
    'Makassar',
    'Batam',
    'Pekanbaru',
    'Tangerang',
    'Depok',
    'Bogor',
    'Bekasi',
    'Denpasar',
    'Yogyakarta',
  ],
  MY: [
    'Kuala Lumpur',
    'Johor Bahru',
    'Ipoh',
    'Shah Alam',
    'Penang',
    'Subang Jaya',
    'Petaling Jaya',
    'Kuching',
    'Kota Kinabalu',
    'Seremban',
  ],
  TH: [
    'Bangkok',
    'Chiang Mai',
    'Nakhon Ratchasima',
    'Hat Yai',
    'Khon Kaen',
    'Chon Buri',
    'Pattaya',
    'Udon Thani',
    'Phuket',
  ],
  PH: [
    'Manila',
    'Quezon City',
    'Davao City',
    'Caloocan',
    'Zamboanga City',
    'Cebu City',
    'Taguig',
    'Antipolo',
    'Pasig',
    'Makati',
  ],
  VN: [
    'Ho Chi Minh City',
    'Hanoi',
    'Da Nang',
    'Hai Phong',
    'Can Tho',
    'Bien Hoa',
    'Hue',
    'Nha Trang',
    'Vung Tau',
  ],
  AU: [
    'Sydney',
    'Melbourne',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Gold Coast',
    'Canberra',
    'Hobart',
    'Darwin',
    'Geelong',
    'Newcastle',
    'Townsville',
  ],
  NZ: [
    'Auckland',
    'Wellington',
    'Christchurch',
    'Hamilton',
    'Tauranga',
    'Dunedin',
    'Palmerston North',
    'Nelson',
    'Rotorua',
  ],

  // ─── South America ────────────────────────────────────────────────────────
  BR: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Porto Alegre',
    'Belém',
    'Goiânia',
    'Campinas',
    'São Luís',
  ],
  AR: [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'Tucumán',
    'La Plata',
    'Mar del Plata',
    'Salta',
    'Santa Fe',
  ],
  CO: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Bucaramanga',
    'Pereira',
    'Santa Marta',
  ],
  CL: [
    'Santiago',
    'Valparaíso',
    'Concepción',
    'La Serena',
    'Antofagasta',
    'Temuco',
    'Rancagua',
    'Talca',
    'Iquique',
  ],
  PE: ['Lima', 'Arequipa', 'Trujillo', 'Chiclayo', 'Piura', 'Iquitos', 'Huancayo', 'Cusco'],

  // ─── Africa ───────────────────────────────────────────────────────────────
  NG: [
    'Lagos',
    'Kano',
    'Ibadan',
    'Abuja',
    'Port Harcourt',
    'Benin City',
    'Maiduguri',
    'Zaria',
    'Aba',
    'Jos',
    'Ilorin',
  ],
  ZA: [
    'Johannesburg',
    'Cape Town',
    'Durban',
    'Pretoria',
    'Port Elizabeth',
    'Bloemfontein',
    'East London',
    'Nelspruit',
    'Polokwane',
    'Pietermaritzburg',
  ],
  KE: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru', 'Eldoret', 'Thika', 'Malindi', 'Kitale'],
  GH: ['Accra', 'Kumasi', 'Tamale', 'Takoradi', 'Cape Coast', 'Tema', 'Sunyani', 'Koforidua'],
  MA: [
    'Casablanca',
    'Rabat',
    'Fez',
    'Marrakech',
    'Agadir',
    'Tangier',
    'Meknes',
    'Oujda',
    'Kenitra',
    'Tetouan',
  ],
  TN: ['Tunis', 'Sfax', 'Sousse', 'Kairouan', 'Bizerte', 'Gabes', 'Ariana', 'Monastir'],
  DZ: [
    'Algiers',
    'Oran',
    'Constantine',
    'Annaba',
    'Blida',
    'Batna',
    'Sétif',
    'Sidi Bel Abbès',
    'Biskra',
  ],
  ZW: ['Harare', 'Bulawayo', 'Chitungwiza', 'Mutare', 'Gweru', 'Kwekwe', 'Kadoma', 'Masvingo'],
  AF: ['Kabul', 'Kandahar', 'Herat', 'Mazar-i-Sharif', 'Jalalabad', 'Kunduz'],
};
