"""Curated list of ~100 common tech and industry skills for autocomplete."""

SKILLS: list[str] = [
    # Programming Languages
    "Python",
    "JavaScript",
    "TypeScript",
    "Java",
    "C#",
    "C++",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "Scala",
    "R",
    "MATLAB",
    # Web Frontend
    "React",
    "Next.js",
    "Vue.js",
    "Angular",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "SASS/SCSS",
    "Redux",
    "GraphQL",
    # Web Backend
    "Node.js",
    "FastAPI",
    "Django",
    "Flask",
    "Express.js",
    "Spring Boot",
    "ASP.NET",
    "Ruby on Rails",
    "Laravel",
    # Databases
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "SQLite",
    "DynamoDB",
    "Cassandra",
    "SQL",
    # Cloud & DevOps
    "AWS",
    "Google Cloud",
    "Azure",
    "Docker",
    "Kubernetes",
    "Terraform",
    "CI/CD",
    "GitHub Actions",
    "Jenkins",
    "Linux",
    "Nginx",
    # Data & ML
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "scikit-learn",
    "Pandas",
    "NumPy",
    "Data Analysis",
    "Data Engineering",
    "Apache Spark",
    "Airflow",
    "dbt",
    "Tableau",
    "Power BI",
    # Mobile
    "iOS Development",
    "Android Development",
    "React Native",
    "Flutter",
    # Security
    "Cybersecurity",
    "Penetration Testing",
    "Network Security",
    # Architecture & Practices
    "Microservices",
    "REST APIs",
    "System Design",
    "Agile",
    "Scrum",
    "DevOps",
    "Test-Driven Development",
    # Soft / General
    "Project Management",
    "Product Management",
    "UX/UI Design",
    "Figma",
    "Technical Writing",
    "Communication",
    "Leadership",
    "Problem Solving",
    # Finance / Business
    "Financial Modeling",
    "Excel",
    "Accounting",
    "Marketing",
    "SEO",
    "Sales",
    "Customer Success",
    "Business Analysis",
    "Operations",
]
